Multiple groups service updates
lexicongovernance/pluraltools-backend pull request #267
Opened 2024-03-13 16:50 UTC by MartinBenediktBusch

2024-03-15 11:44 UTC, diegoalzate commented
## proposed solution for groups
```
export async function upsertUsersToGroups(
  dbPool: PostgresJsDatabase<typeof db>,
  userId: string,
  newGroupIds: string[],
): Promise<db.UsersToGroups[] | null> {
  try {
    // assume the groupLabelId is in user_to_groups
    // query groups to get groupLabelId
    const groups = await dbPool.groups.findMany({ where: { id: { in: newGroupIds } } });

    // STEP 1
    // changes to user-groups without groupLabelId
    // same as logic as before as they are probably affiliations
    //    i.e  delete all user to groups that we found have no groupLabelId, where userId is my userId
    //    i.e  insert all user to groups with null groupLabelId, where userId is my userId

    // STEP 2
    // changes to user-groups with groupLabelId (groups that are meant for event participation)
    //    i.e delete all user to groups that we found have groupLabelId and userId
    //    i.e insert all user to groups that we found have groupLabelId and userId
  } catch (error) {
    console.error('Error upserting user groups: ' + JSON.stringify(error));
    return null;
  }
}
```

2024-03-18 13:16 UTC, diegoalzate requested changes

2024-03-18 13:16 UTC, diegoalzate commented on src/db/usersToGroups.ts
> +  groupLabelId: uuid('group_label_id').references(() => groupCategories.id),
lets call this groupCategoryId

2024-03-18 13:16 UTC, diegoalzate commented on src/routers/groups.ts
> +    '/groups/:userId/:groupLabelId',
groups is already prepended in the apiRouter, or if it is not then it should be so we do not repeat it here

2024-03-18 13:16 UTC, diegoalzate commented on src/routers/groups.ts
> +    '/groups/:userId/:groupLabelId',
also lets change groupLabelId to groupCategoryId

2024-03-18 13:16 UTC, diegoalzate commented on src/routers/groups.ts
> +    '/groups/:userId/:groupLabelId',
there are a couple issues on the routes here:

1. for express there is no way to differentiate /groups/:groupLabelId and /groups/:userId as they are just wild cards.
2. A hierarchy issue, if we want to do getGroupsPerUser i think it should go to a user router with the structure: `users/:userId/group-categories/:groupCategoryId/groups` and to get all groups for a user i think there is already a route. Also to get groups per group cateogry might require a new router that makes the url look like `/group-categories/:groupCategoryId/groups`

2024-03-18 13:41 UTC, MartinBenediktBusch commented on src/db/usersToGroups.ts
> +  groupLabelId: uuid('group_label_id').references(() => groupCategories.id),
Done.

2024-03-18 14:15 UTC, diegoalzate approved these changes

2024-03-18 14:15 UTC, merged